### ISSUE TITLE
Can't get console version to build.

### ISSUE THREAD

**Issue by vbmark** [Forays/ForaysIntoNorrendrin#1]

**Comment by derrickcreamer** [comment]
Thanks for pointing out that the ConsoleForays.csproj file wasn't up to date. It's now fixed and updated to version 0.8.4.

**Comment by vbmark** [comment]
Thank you Derrick.  I have been searching for about two months for a good code base to fork and I really like what you've done.  I have an idea that I want to flesh out and I will give you full credit.
