### ISSUE TITLE
?knowledge and items in chests

### ISSUE THREAD

**Issue by hubertig** [Forays/ForaysIntoNorrendrin#2]
Hi, not sure if this is the proper way to inform you about bugs.

I noticed that a ?knowledge says that it will ID all stuff in my pack and on the level.
I used one and then found an orb in a chest on the same level, but the orb was not ID-ed.

Anyways, cool game. Just getting into it, really like the emphasis on environment interaction.

**Comment by derrickcreamer** [comment]
Oh, hey! This is okay for reporting bugs, but (as you can see) it can take me a while to notice a new issue.

I'm not sure whether to consider this a bug or not. The scroll also doesn't identify items carried by monsters. In any case, this might change in future releases.

Thanks!
